export const MOCK_PRODUCTS = [
    { id: '1', name: 'Arroz Prato Fino 5kg', price: 28.90, category: 'mercearia', brand: 'Prato Fino' },
    { id: '2', name: 'Arroz Camil 5kg', price: 26.50, category: 'mercearia', brand: 'Camil' },
    { id: '3', name: 'Arroz Tio João 5kg', price: 29.90, category: 'mercearia', brand: 'Tio João' },
    { id: '4', name: 'Feijão Carioca Camil 1kg', price: 8.90, category: 'mercearia', brand: 'Camil' },
    { id: '5', name: 'Feijão Preto Kicaldo 1kg', price: 7.50, category: 'mercearia', brand: 'Kicaldo' },
    { id: '6', name: 'Leite Integral Piracanjuba 1L', price: 4.89, category: 'laticinios', brand: 'Piracanjuba' },
    { id: '7', name: 'Leite Integral Ninho 1L', price: 5.29, category: 'laticinios', brand: 'Ninho' },
    { id: '8', name: 'Café Pilão 500g', price: 18.90, category: 'mercearia', brand: 'Pilão' },
    { id: '9', name: 'Café Melitta 500g', price: 19.50, category: 'mercearia', brand: 'Melitta' },
    { id: '10', name: 'Açúcar Refinado União 1kg', price: 5.40, category: 'mercearia', brand: 'União' },
    { id: '11', name: 'Óleo de Soja Lisa 900ml', price: 6.90, category: 'mercearia', brand: 'Lisa' },
    { id: '12', name: 'Macarrão Renata 500g', price: 4.50, category: 'mercearia', brand: 'Renata' },
    { id: '13', name: 'Molho de Tomate Pomarola', price: 3.20, category: 'mercearia', brand: 'Pomarola' },
    { id: '14', name: 'Sabão em Pó Omo 800g', price: 14.90, category: 'limpeza', brand: 'Omo' },
    { id: '15', name: 'Detergente Ypê 500ml', price: 2.50, category: 'limpeza', brand: 'Ypê' },
    { id: '16', name: 'Hambúrguer Sadia 672g', price: 18.90, category: 'carnes', brand: 'Sadia' },
    { id: '17', name: 'Refrigerante Coca-Cola 2L', price: 9.50, category: 'bebidas', brand: 'Coca-Cola' },
    { id: '18', name: 'Cerveja Heineken 330ml', price: 5.90, category: 'bebidas', brand: 'Heineken' },
    { id: '19', name: 'Papel Higiênico Neve 12un', price: 24.90, category: 'higiene', brand: 'Neve' },
    { id: '20', name: 'Creme Dental Colgate', price: 7.90, category: 'higiene', brand: 'Colgate' },
];
